version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://lachve:${DB_PASSWORD}@clustertfm.bftl8.mongodb.net/TFM?retryWrites=true&w=majority&appName=ClusterTFM
    restart: unless-stopped
